### ISSUE TITLE
ExtJS 6 support

### ISSUE THREAD

**Issue by hbulens** [wilk/ExtJS-WebWorker#1]
It's been three years since the last commit so is a long shot, but I was wondering if you could add support for ExtJS 6?

**Comment by wilk** [comment]
@hbulens 

I'm sorry but I forgot to put the message on the README.md months ago: https://github.com/wilk/ExtJS-WebWorker/commit/1d201d9244dca2ee75892e3962b8943ca883a009

If you need support for ExtJS 6, feel free to fork it and to continue the development.
